# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: project_x_development
  pool: 5
  username: root
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: project_x_test
  pool: 5
  username: root
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: project_x_production
  pool: 5
  username: root
  password:
